# Generated by Django 4.1.3 on 2022-11-19 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=30, verbose_name='Марка')),
                ('model', models.CharField(max_length=30, verbose_name='Модель')),
                ('engine_model', models.CharField(max_length=30, verbose_name='Номер двигателя')),
                ('chassis_number', models.CharField(max_length=30, verbose_name='Номер шасси')),
                ('vin', models.CharField(max_length=17, verbose_name='VIN')),
                ('state_number', models.CharField(max_length=8, verbose_name='Гос. номер')),
                ('release_year', models.IntegerField(verbose_name='Год выпуска')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='ElectricCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=30, verbose_name='Марка')),
                ('model', models.CharField(max_length=30, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Электрический автомобиль',
                'verbose_name_plural': 'Электрические автомобили',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
                ('passport_num', models.CharField(max_length=20, verbose_name='Номер паспорта')),
                ('passport_serial', models.CharField(max_length=20, verbose_name='Серия паспорта')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.carinfo', verbose_name='Автомобиль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Информация о пользователе',
                'verbose_name_plural': 'Информация о пользователях',
            },
        ),
    ]
