# Generated by Django 4.1.3 on 2022-11-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electriccar',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='electriccar',
            name='model',
        ),
        migrations.AddField(
            model_name='electriccar',
            name='auto',
            field=models.CharField(default=None, max_length=60, verbose_name='Автомобиль'),
            preserve_default=False,
        ),
    ]
