# Generated by Django 4.1.3 on 2022-11-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_electriccar_mark_remove_electriccar_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinfo',
            old_name='engine_model',
            new_name='engine_number',
        ),
        migrations.RenameField(
            model_name='carinfo',
            old_name='release_year',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='chassis_number',
        ),
        migrations.AddField(
            model_name='carinfo',
            name='category',
            field=models.CharField(default=111, max_length=3, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carinfo',
            name='color',
            field=models.CharField(default=1, max_length=20, verbose_name='Цвет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carinfo',
            name='power_hp',
            field=models.CharField(default=111, max_length=20, verbose_name='Л.с.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carinfo',
            name='power_kwt',
            field=models.CharField(default=111, max_length=20, verbose_name='Кв./ч.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carinfo',
            name='type',
            field=models.CharField(default=111, max_length=20, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
