# Generated by Django 4.1.3 on 2022-11-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expertises', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElectricCars',
            new_name='ElectricCar',
        ),
    ]
