# Generated by Django 4.1.3 on 2022-11-19 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expertises', '0002_rename_electriccars_electriccar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectricCar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='car_info_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_info_id',
        ),
        migrations.DeleteModel(
            name='CarInfo',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
