# Generated by Django 4.1.3 on 2022-11-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expertises', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_info_id',
            new_name='user',
        ),
    ]
