# Generated by Django 4.1.3 on 2022-11-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expertises', '0005_rename_user_info_id_userinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='car_info_id',
            new_name='car',
        ),
    ]
