# Generated by Django 4.1.3 on 2022-11-19 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expertises', '0007_rename_login_electriccar_mark_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carinfo',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='electriccar',
            options={'verbose_name': 'Электрический автомобиль', 'verbose_name_plural': 'Электрические автомобили'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'Информация о пользователе', 'verbose_name_plural': 'Информация о пользователях'},
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='chassis_number',
            field=models.CharField(max_length=30, verbose_name='Номер шасси'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='engine_model',
            field=models.CharField(max_length=30, verbose_name='Номер двигателя'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='mark',
            field=models.CharField(max_length=30, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='model',
            field=models.CharField(max_length=30, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='release_year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='state_number',
            field=models.CharField(max_length=8, verbose_name='Гос. номер'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='vin',
            field=models.CharField(max_length=17, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='electriccar',
            name='mark',
            field=models.CharField(max_length=30, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='electriccar',
            name='model',
            field=models.CharField(max_length=30, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expertises.carinfo', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='passport_num',
            field=models.CharField(max_length=20, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='passport_serial',
            field=models.CharField(max_length=20, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='patronymic',
            field=models.CharField(max_length=20, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='second_name',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
